import 'axios';
import 'babel-polyfill';
import 'jquery';
import 'lodash';
import 'react';
import 'react-autosuggest';
import 'react-bootstrap';
import 'react-cookie';
import 'react-dom';
import 'react-redux';
import 'react-router';
import 'react-router-redux';
import 'react-router-scroll';
import 'react-sortable-hoc';
import 'redux';
import 'redux-thunk';
import 'toastr';

import './vendor.scss';
