variables:
  DOCKER_HOST: tcp://docker:2375/

stages:
  - build
  - deploy

build:
  image: docker:stable
  services:
    - docker:dind
  stage: build
  except:
    - master
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .

build_and_push:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  only:
    - master
  script:
    - docker login -u $CI_REGISTRY_USER -p $ACCESS_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

deploy:
  stage: deploy
  only:
    - master
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan jakubricar.cz >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - scp docker/docker-compose.yml ci@jakubricar.cz:/srv/docker/cookbook
    - ssh ci@jakubricar.cz 'cd /srv/docker/cookbook && docker-compose pull && docker-compose up -d'
