stages:
  - build
  - deploy

variables:
  NGINX_VHOSTD_DIR: /srv/nginx/vhost.d
  TARGET_DIR: /home/gitlab-runner/www/cookbook_$CI_COMMIT_REF_SLUG/

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build-api:
  stage: build
  tags:
    - shared
  image: docker:stable
  services:
    - docker:dind
  script:
    - cd api
    - docker build -t "$CI_REGISTRY_IMAGE/api:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/api:$CI_COMMIT_REF_SLUG"

build-web:
  stage: build
  tags:
    - shared
  image: docker:stable
  services:
    - docker:dind
  script:
    - cd web
    - docker build -t "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE/web:$CI_COMMIT_REF_SLUG"

deploy-feature:
  stage: deploy
  except:
    - master
    - production
    - tags
  tags:
    - hukot-web
  when: manual
  script:
    - rsync -a --delete deploy/ "$TARGET_DIR"
    - rsync -a deploy/vhost.d/ "$NGINX_VHOSTD_DIR"
    - cd "$TARGET_DIR"
    - envsubst < .env.feature > .env
    - docker-compose pull
    - docker-compose down --remove-orphans --rmi local
    - docker-compose up -d
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://$CI_COMMIT_REF_SLUG.zradelnik.eu
    on_stop: stop-env-feature

stop-env-feature:
  stage: deploy
  except:
    - master
    - production
    - tags
  tags:
    - hukot-web
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  when: manual
  script:
    - cd "$TARGET_DIR"
    - docker-compose down --remove-orphans --volumes --rmi local
    - docker-compose rm
    - cd ~
    - rm -rf "$TARGET_DIR"

deploy:
  stage: deploy
  only:
    - master
    - production
  tags:
    - hukot-web
  script:
    - rsync -a --delete deploy/ "$TARGET_DIR"
    - rsync -a deploy/vhost.d/ "$NGINX_VHOSTD_DIR"
    - cd "$TARGET_DIR"
    - '[ "$CI_COMMIT_REF_SLUG" = production ] && envsubst < .env.production > .env || envsubst < .env.staging > .env'
    - docker-compose pull
    - docker-compose down --remove-orphans
    - docker-compose up -d
