stages:
  - build
  - deploy

variables:
  NGINX_VHOSTD_DIR: /srv/nginx/vhost.d
  DEV_DIR: /home/gitlab-runner/www/cookbook_$CI_COMMIT_REF_SLUG/
  PROD_DIR: /home/gitlab-runner/www/cookbook_prod/

build:
  stage: build
  tags:
    - shared
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

deploy-dev:
  stage: deploy
  except:
    - develop
    - master
    - tags
  tags:
    - hukot-web
  when: manual
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - rsync -a --delete deploy/ $DEV_DIR
    - rsync -a deploy/vhost.d/ "$NGINX_VHOSTD_DIR"
    - cd $DEV_DIR
    - envsubst < ".env.dev" > ".env"
    - docker-compose pull
    - docker-compose down --remove-orphans --rmi local
    - docker-compose up -d
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://$CI_COMMIT_REF_SLUG.zradelnik.eu
    on_stop: stop-env-dev

stop-env-dev:
  stage: deploy
  except:
    - develop
    - master
    - tags
  tags:
    - hukot-web
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  when: manual
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - cd $DEV_DIR
    - docker-compose down --remove-orphans --volumes --rmi local
    - docker-compose rm
    - cd ~
    - rm -rf $DEV_DIR

deploy-test:
  stage: deploy
  only:
    - develop
  tags:
    - hukot-web
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - rsync -a --delete deploy/ $DEV_DIR
    - rsync -a deploy/vhost.d/ "$NGINX_VHOSTD_DIR"
    - cd $DEV_DIR
    - envsubst < ".env.dev" > ".env"
    - docker-compose pull
    - docker-compose down --remove-orphans
    - docker-compose up -d

deploy-prod:
  stage: deploy
  only:
    - master
  tags:
    - hukot-web
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - rsync -a --delete deploy/ $PROD_DIR
    - rsync -a deploy/vhost.d/ "$NGINX_VHOSTD_DIR"
    - cd $PROD_DIR
    - envsubst < ".env.prod" > ".env"
    - docker-compose pull
    - docker-compose down --remove-orphans
    - docker-compose up -d
