FROM node:6-alpine

RUN mkdir -p /srv/app
WORKDIR /srv/app

COPY ./client/package.json ./client/yarn.lock ./client/
COPY ./server/package.json ./server/yarn.lock ./server/

RUN cd client; yarn
RUN cd server; yarn

COPY . .

EXPOSE 4000 4001

CMD ./start-dev.sh
