singleQuote: true
# arrowParens: avoid
plugins:
  - '@trivago/prettier-plugin-sort-imports'
importOrder:
  - '<THIRD_PARTY_MODULES>'
  - '@/(.*)'
  - '^(?!.*\\.css$)[../]'
  - '^(?!.*\\.css$)[./]'
  - '\\.css$'
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderCaseInsensitive: true
