version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.5.0
    steps:
      - checkout
      - run:
          name: Update yarn
          command: "sudo npm install -g yarn@latest"
      - restore_cache:
          key: v1-dependency-cache-server-{{ checksum "server/package.json" }}
      - restore_cache:
          key: v1-dependency-cache-client-{{ checksum "client/package.json" }}
      - run:
          name: Install dependencies - server
          command: "cd server && yarn"
      - run:
          name: Install dependencies - client
          command: "cd client && yarn"
      - save_cache:
          key: v1-dependency-cache-server-{{ checksum "server/package.json" }}
          paths:
            - server/node_modules
      - save_cache:
          key: v1-dependency-cache-client-{{ checksum "client/package.json" }}
          paths:
            - client/node_modules
      - run:
          name: Test
          command: "cd client && yarn test"
      - run:
          name: Build
          command: "cd scripts && ./build.sh"
      - persist_to_workspace:
          root: .
          paths:
            - dist/*

  deploy_development:
    docker:
      - image: circleci/node:8.5.0
    steps:
      - setup_remote_docker:
          version: 17.07.0-ce
      - attach_workspace:
          at: .
      - run:
          name: Docker build and push
          command: |
            docker build -t "docker.jakubricar.cz/cookbook:dev" .
            docker login -u $DOCKER_USER -p $DOCKER_PASS docker.jakubricar.cz
            docker push "docker.jakubricar.cz/cookbook:dev"
      - deploy:
          command: "ssh -o StrictHostKeyChecking=no ricar@jakubricar.cz './cookbook/start.sh dev'"

  deploy_production:
    docker:
      - image: circleci/node:8.5.0
    steps:
      - setup_remote_docker:
          version: 17.07.0-ce
      - attach_workspace:
          at: .
      - run:
          name: Docker build and push
          command: |
            docker build -t "docker.jakubricar.cz/cookbook:latest" .
            docker login -u $DOCKER_USER -p $DOCKER_PASS docker.jakubricar.cz
            docker push "docker.jakubricar.cz/cookbook:latest"
      - deploy:
          command: "ssh -o StrictHostKeyChecking=no ricar@jakubricar.cz './cookbook/start.sh prod'"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_development:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy_production:
          requires:
            - build
          filters:
            branches:
              only: master
