version: '3.2'

services:
  db:
    image: mongo:4.0
    volumes:
      - type: bind
        source: ~/dev/private/mongo_data/cookbook
        target: /data/db

  web:
    image: cookbook
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://db/cookbook
    ports:
      - '5000:3000'
