version: '3'

services:
  db:
    image: mongo:3.4
    restart: always
    networks:
      - cookbook
    volumes:
      - /srv/docker/cookbook/data:/data/db

  web:
    image: docker.jakubricar.cz/cookbook:latest
    restart: always
    networks:
      - cookbook
      - web
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://db/cookbook
      - VIRTUAL_HOST=zradelnik.jakubricar.cz
      - LETSENCRYPT_HOST=zradelnik.jakubricar.cz
      - LETSENCRYPT_EMAIL=***REMOVED***

networks:
  cookbook:
  web:
    external: true
