version: '3'

services:
  db:
    image: mongo:3.4
    volumes:
      - ~/dev/private/mongo_data:/data/db

  web:
    image: cookbook
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://db/cookbook
    ports:
      - '5000:3000'
