export const RECIPES_REQUEST = 'RECIPES_REQUEST';
export const RECIPES_SUCCESS = 'RECIPES_SUCCESS';
export const RECIPES_FAILURE = 'RECIPES_FAILURE';

export const RECIPE_DETAIL_REQUEST = 'RECIPE_DETAIL_REQUEST';
export const RECIPE_DETAIL_SUCCESS = 'RECIPE_DETAIL_SUCCESS';
export const RECIPE_DETAIL_FAILURE = 'RECIPE_DETAIL_FAILURE';
