export const REQUEST_RECIPES = 'REQUEST_RECIPES';
export const RECEIVE_RECIPES = 'RECEIVE_RECIPES';
export const REQUEST_RECIPE_DETAIL = 'REQUEST_RECIPE_DETAIL';
export const RECEIVE_RECIPE_DETAIL = 'RECEIVE_RECIPE_DETAIL';
