version: '3.6'

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db/cookbook
    tty: true

  db:
    image: mongo:4.2
    volumes:
      - type: bind
        source: ~/dev/private/mongo_data/cookbook
        target: /data/db
