version: '3.2'

services:
  db:
    image: mongo:4.2
    ports:
      - '27017:27017'
    volumes:
      - type: bind
        source: ~/dev/private/mongo_data/cookbook
        target: /data/db

  admin:
    image: mongo-express
    ports:
      - '8081:8081'
    depends_on:
      - db
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_URL: mongodb://db/cookbook
