service: zradelnik

custom:
  serverless-offline:
    httpPort: 4000
  recipeImagesS3Bucket: zradelnik-img-${opt:stage}

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 256
  timeout: 3
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action: s3:*
      Resource: 'arn:aws:s3:::${self:custom.recipeImagesS3Bucket}/*'
  environment:
    RECIPE_IMAGES_S3_BUCKET: ${self:custom.recipeImagesS3Bucket}

functions:
  createThumbnail:
    handler: thumbnail/create.handler
    events:
      - s3:
          bucket: ${self:custom.recipeImagesS3Bucket}
          event: s3:ObjectCreated:Put
          rules:
            - prefix: full/
  recreateThumbnail:
    handler: thumbnail/recreate.handler

resources:
  Resources:
    RecipeImagesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${self:custom.recipeImagesS3Bucket}
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: 'arn:aws:s3:::${self:custom.recipeImagesS3Bucket}/*'
