env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
rules:
  '@typescript-eslint/no-non-null-assertion': 'off'
  import/order:
    - warn
    - newlines-between: always
      alphabetize:
        order: 'asc'
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
      allowSeparatedGroups: true
